name: Liquibase CI/CD

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Name of the Liquibase changelog file'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Download and install Liquibase
      run: |
          wget -q https://github.com/liquibase/liquibase/releases/download/v4.8.0/liquibase-4.8.0.tar.gz
          tar -xzf liquibase-4.8.0.tar.gz
          chmod +x liquibase
          sudo mv liquibase /usr/local/bin/

    - name: Run Liquibase update
      run: |
          liquibase --changeLogFile=master_changelog.xml \
                    --url=jdbc:mysqlserver://liquibasemysqlserver.mysql.database.azure.com;databaseName=liquibasedatabase \
                    --username=liquibaseserver \
                    --password=dbops123@ \
                    updates/liquibase.properties update
