name: Liquibase Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  liquibase:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Download Liquibase
      run: |
        wget -O liquibase.tar.gz https://github.com/liquibase/liquibase/releases/download/v4.8.0/liquibase-4.8.0.tar.gz
        tar -xzf liquibase.tar.gz
        chmod +x liquibase
        sudo mv liquibase /usr/local/bin/

    - name: Execute Liquibase
      run: |
         # liquibase.bat --changeLogFile=001_create_table.xml --defaultsFile=liquibase.properties update 

          liquibase.bat --changeLogFile=changelogs/changesets/${{ github.event.inputs.filename }} --defaultsFile=liquibase.properties update

         # liquibase.bat --changeLogFile=changelogs/changesets/master_changelog.xml --defaultsFile=changelogs/changesets/liquibase.properties update
