name: Liquibase CI/CD

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Name of the Liquibase changelog file'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Liquibase update
      run: |
          liquibase --changeLogFile=changelog.xml \
                    --url=jdbc:mysql://localhost:3306/mydatabase \
                    --username=myuser \
                    --password=mypassword \
                    updates/liquibase.properties update

      shell: cmd
