name: Liquibase Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  liquibase:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Download Liquibase
      run: |
        wget -O liquibase.tar.gz https://github.com/liquibase/liquibase/releases/download/liquibase-parent-4.8.0/liquibase-4.8.0.tar.gz
        tar -xzf liquibase.tar.gz
        chmod +x liquibase
        sudo mv liquibase /usr/local/bin/

    - name: Run Liquibase Update
      run: |
        liquibase --changeLogFile=db/changelog.xml \
                  --url=jdbc:mysql://localhost:3306/mydatabase \
                  --username=myusername \
                  --password=mypassword \
                  update
